### ISSUE TITLE
[Question] Access $t inside a persistent layout

### ISSUE THREAD

**Issue by mariusberget92** [xiCO2k/laravel-vue-i18n#102]
Is it possible to access $t inside the persistent layout? I am trying to set a page title based on plural form of a model, needing `$t('User|Users', 2)` like this: 

``` js
layout: (h, page) => {
  return h(VLayout, { pageTitle: $t('User|Users', 2) }, () => page);
},
```
It throws a undefined error. I did kind of expect it though, just wondering if there's a way to access $t in there.

**Comment by xiCO2k** [comment]
you have to use `trans()` method..

```js
import { trans } from 'laravel-vue-i18n'`.
