### ISSUE TITLE
Webpack is not generating PHP language files

### ISSUE THREAD

**Issue by yansem** [xiCO2k/laravel-vue-i18n#110]
Doesn't work with:
laravel v.8.83.27
laravel-vue-i18n v.2.4.0

But works with: 
laravel v8.51.0
laravel-vue-i18n v.2.3.4

**Comment by yansem** [comment]
Works on another project with Laravel 8.51.0 (doesn't work on Laravel 8.87.27). I realized that console.log is output in the terminal with "npm run dev".
langPath is correct in both projects (C:\Users\User\PhpstormProjects\project\resources/lang), but there are some differences in the dist/mix.js

**Comment by xiCO2k** [comment]
Will check

**Comment by xiCO2k** [comment]
Fixed on `v2.4.1`.

Thanks for the report.

**Comment by yansem** [comment]
Thank you!
