### ISSUE TITLE
Feature request default tChoice number to 1

### ISSUE THREAD

**Issue by timyourivh** [xiCO2k/laravel-vue-i18n#113]
### The problem

When I use
```js
tChoice('foo') // Without second param
```
It throws an error:

![image](https://user-images.githubusercontent.com/60601502/227473576-c65f9356-5415-4576-9bae-a90b8f5a629d.png)

And causes my app to not render the view.

### The solution

It would be great to prevent this error and have the `number` param default to 1 if nothing is defined.
Or be able to use `t('foo')` which would then pick the first one. (my preference)

### Nice to haves

Support for negative and zero.
It now picks the last unless specifically defined with brackets. For example:
```json
{
  "foo": "foo|foos",
  "bar": "{*,1}bar|bars",
}
```
```js
tChoice('foo', -1) // Expected: "foo". Outputs: "foos".
tChoice('foo', 0)  // Expected: "foo". Outputs: "foos".

tChoice('bar', -1) // Expected: "bar". Outputs: "bar".
tChoice('bar', 0)  // Expected: "bar". Outputs: "bar".
```

**Comment by xiCO2k** [comment]
Hey @timyourivh will check that out.
