### ISSUE TITLE
Support for html in translation strings

### ISSUE THREAD

**Issue by jezzdk** [xiCO2k/laravel-vue-i18n#114]
Some of my translation strings contain html, but when the strings are displayed the html breaks. This is because the "/" characters are replaced with ".".

Example:

`<div v-html="$t('Hello <strong>:name</strong>!', { name: 'World' })" />`

outputs:

`<div>Hello <strong>World<.strong>!</div>`

Is there a way to circumvent this behavior? (without removing the html from the translations...)

**Comment by xiCO2k** [comment]
Thanks for the issue, will take a look on this.
