### ISSUE TITLE
Translations do not load if app is refreshed on certain pages

### ISSUE THREAD

**Issue by chris-hud** [xiCO2k/laravel-vue-i18n#136]
I've gone through every existing issue and haven't been able to solve this yet. 
When my app initializes at certain pages, or is refreshed on certain pages, the translation files return as expected and everything works. However on some pages which I can't find any difference on, the translation files are not loaded. 

I have attempted the config with SSR mode and with standard vite mode, as well as mounting the app after load as described here
https://github.com/xiCO2k/laravel-vue-i18n/issues/93#issuecomment-1425683737
```
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(i18nVue, {
                resolve: async lang => {
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                }
            })
            ...
            ...
            ...
            .use(ZiggyVue, Ziggy)
            .mount(el);
    },
});
```

In looking in the chrome network tab, I can confirm that doing a refresh on the /profile page or the /leads page, the language file is not loaded, however doing the same refresh on the /messages or the /dashboard pages both will load the file. All of these pages are wrapped in the same layout. Once the file has been loaded on a page that loads it, all the pages work as expected unless a refresh is done on one of the other pages.

Any Ideas?

**Comment by chris-hud** [comment]
Still trying to work through this.
if a user navigates to /login, everything works fine
if they navigate to /register, it fails.

            resolve: async lang => {
                    console.log('in resolve');
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                },
                
When I log this on login and register routes, it only prints on the login route. So this resolve for some reason is not always running.

**Comment by chris-hud** [comment]
If I install the plugin like this:
                .use(i18nVue, {       
                resolve: async lang => {
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                }
            })
            .use(ZiggyVue, Ziggy)
            .mount(el);
            
The login page works perfectly, but the register page loads with no translations. 

If instead I mount the app in the onLoad of the plugin, like this:
            return app.use(i18nVue, {
                 resolve: async lang => {
                     const langs = import.meta.glob('../../lang/*.json');
                     return await langs[`../../lang/${lang}.json`]();
                 },
                onLoad: () => {
                    app.mount(el);
                }
            })

The login page still works perfectly, but now the register page does not render at all, and i see an error for 
    Uncaught (in promise) TypeError: _ctx.$t is not a function

I notice that I get the same error if I comment out the app.use() of this plugin entirely. This is leading me to think that vue is not registering this plugin at all if the app is initialized on /register. 

I'm not doing anything unique in my setup, very straightforward vite/inertia build as instructed in the inertia docs.

**Comment by musiwei** [comment]
I have the same issue. I'm using Laravel 10 with Vite. If I press refresh on a page other than the homepage, all the translations are removed.  @xiCO2k

**Comment by xiCO2k** [comment]
Hey I was unable to replicate that, its possible for you guys to set up a repo, where I can find that issue?

Thanks.

**Comment by musiwei** [comment]
I should probably provide more context, I am making the below change to fix the flickering issue as [mentioned and solved here](https://github.com/xiCO2k/laravel-vue-i18n/issues/93): 

Previous:
```php
return app.use(i18nVue, {
                fallbackLang: 'cn',
                resolve: async lang => {
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                }
            }).mount(el);
```

Now (good!):
```php
return app.use(i18nVue, {
                fallbackLang: 'cn',
                resolve: async lang => {
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                },
                onLoad: () => {
                    app.mount(el);
                }
            });
```

After I change the mount, it works fine for all the regular routes, but it shows 
`Uncaught (in promise) TypeError: _ctx.$t is not a function` 
to Laravel signed URL like:
 `http://example.local/order/966a0586-863b-4466-bad4-4efcf130e945/self-serve/fill?expires=1688997806&token=MdguGErClKYnd5acIQwR&signature=623c4a7a31e5543e3d8475a4a679cbcb46a6311a97f6bf03817f793cf022b2c9` 

You might wonder if it's a login issue since the signed URL does not require a login, but the login page works fine.

Here is my Vite setting: 
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import i18n from 'laravel-vue-i18n/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        i18n(),
    ],
});

```

I am writing you code to generate a signed URL anywhere. Simply paste this in any controller to get the URL and try it in an incognito window:

```php
$token = Str::random(20);
$url = \Illuminate\Support\Facades\URL::temporarySignedRoute(
    'dashboard', now()->addHours(2), ['token' => $token]
);
dd($url);
```

**Comment by musiwei** [comment]
Hey Francis, 

I found the solution and I think this may be helpful for you to patch it.

This should be beneficial to anyone who is suffering the same issue, too:

**Solution: do not use `trans()` in `defineProps`.** 

![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/2687655/4faef423-a534-4f11-87c8-96ab5cfec2cb)

**Comment by xiCO2k** [comment]
Yes that I don't think will work, but if you do like:

```js
defineProps({
    label: {
        type: String,
        default: () => trans('FileUploadWidget.Files'),
    }
});
```

I think this should work.
