### ISSUE TITLE
Multiple occurrence of variable issue

### ISSUE THREAD

**Issue by xiki808** [xiCO2k/laravel-vue-i18n#137]
Hi, this issue is showing up again: https://github.com/xiCO2k/laravel-vue-i18n/issues/91

I'm with version 2.5.1

**Comment by xiCO2k** [comment]
got it, will check that out.

**Comment by xiCO2k** [comment]
I was unable to reproduce it, and there is a test to reproduce it.

Check this:
https://github.com/xiCO2k/laravel-vue-i18n/blob/main/test/translate.test.ts#L84-L90

Also you can try using the `$t()` helper instead.
