### ISSUE TITLE
Support for php translations files?

### ISSUE THREAD

**Issue by DanielvdSpoel** [xiCO2k/laravel-vue-i18n#14]
Is ther support for php translations files? All the examples i saw are using .json files

**Comment by xiCO2k** [comment]
I really want to have a loader to add the support for `.php` files, unfortunately I did not had the time to do it.

Feel free to contribute, I would love that.

Thanks

**Comment by DanielvdSpoel** [comment]
Can you maby point me to the direction where the .json files are loaded? Can't seem to find the part that is responsible for it

**Comment by xiCO2k** [comment]
Hey @DanielvdSpoel just publish a new version (v1.4.0) that adds the support for `.php` files.

Thanks for the feedback.
