### ISSUE TITLE
Key name flashes on screen before translation is displayed

### ISSUE THREAD

**Issue by travisricks** [xiCO2k/laravel-vue-i18n#141]
I've noticed that when the page first loads I see a flash of all the key names, e.g. 'microsite.nav-home' and then the translation, 'Home', displays. I'm not sure how to fix this.

laravel-vue-i18n: 2.6.1
vite: 4.4.1
vue: 3.3.4
@inertiajs/vue3: 1.0.9

![Screenshot-001894-2023-07-13at11 08 49](https://github.com/xiCO2k/laravel-vue-i18n/assets/289841/3517095d-caff-4a8f-ba6b-f901b6c075b9)

Thanks for any help you can provide!

**Comment by xiCO2k** [comment]
The solution for that, is this:

https://github.com/xiCO2k/laravel-vue-i18n/issues/117#issuecomment-1627295319
