### ISSUE TITLE
Wont work with inerta/vue SSR

### ISSUE THREAD

**Issue by nezaboravi** [xiCO2k/laravel-vue-i18n#147]
When is in SSR mode, it would not translate.

NON SSR mode:
<img width="529" alt="image" src="https://github.com/xiCO2k/laravel-vue-i18n/assets/1515172/131afcb9-be9d-4bf6-a8dc-cf201dc382c4">

➜  invoicing git:(payment) ✗ php artisan inertia:start
Starting SSR server on port 13714...
Inertia SSR server started.
[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
TypeError: _ctx.$t is not a function

SSR mode:
<img width="372" alt="image" src="https://github.com/xiCO2k/laravel-vue-i18n/assets/1515172/a99ec9d6-5186-47d6-b791-07061dfedbfd">

Code:
<img width="1264" alt="image" src="https://github.com/xiCO2k/laravel-vue-i18n/assets/1515172/22fb1ea1-bdbd-4a0e-a826-59500f59aa16">

**Comment by xiCO2k** [comment]
Hey @nezaboravi did you follow the instructions for the SSR?

https://github.com/xiCO2k/laravel-vue-i18n#ssr-server-side-rendering-1

**Comment by nezaboravi** [comment]
Did so, works now, my apologies

**Comment by nezaboravi** [comment]
Works now as suggested
