### ISSUE TITLE
Cannot load language files

### ISSUE THREAD

**Issue by davidtovt** [xiCO2k/laravel-vue-i18n#15]
Hello,

Why I get the following error?

```
GET http://***.com/js/resources_lang_hu_json.js net::ERR_ABORTED 404 (Not Found)
Uncaught (in promise) TypeError: Cannot load lang: hu file: Loading chunk resources_lang_hu_json failed.
```

The resources/lang/en.json file exists.

**Comment by xiCO2k** [comment]
Hey @davidtovt are you using webpack?

Also can you share the code where you import the code?

**Comment by xiCO2k** [comment]
Weird case, try this since I miss the $ sign

```js
resolve: (lang) => import(`../lang/${lang}.json`),
```

**Comment by davidtovt** [comment]
It is not working.

In laravel-vue-i18n/src/index.ts there is a line which not used anywhere:
`import { LanguageJsonFileInterface } from './interfaces/language-json-file'`
It is not problem?
