### ISSUE TITLE
Error: Unknown variable dynamic import: ../lang/en.json

### ISSUE THREAD

**Issue by stevebauman** [xiCO2k/laravel-vue-i18n#151]
When following the default Vite instructions and I load my website, the below error flashes for a second, and then disappears. Everything still works, but not sure what the cause of this is:

```js
import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

createApp()
    .use(i18nVue, {
        resolve: async lang => {
            const langs = import.meta.glob('../../lang/*.json');

            return await langs[`../../lang/${lang}.json`]();
        }
    })
    .mount('#app');
```

![error](https://github.com/xiCO2k/laravel-vue-i18n/assets/6421846/d7e35156-693c-4bc5-80f4-42c257066da2)

However, if I update the `resolve` callback to include a `php_` prefix in the `return await` statement, the error no longer appears and everything functions normally:

```diff
import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

createApp()
    .use(i18nVue, {
        resolve: async lang => {
            const langs = import.meta.glob('../../lang/*.json');

-           return await langs[`../../lang/${lang}.json`]();
+           return await langs[`../../lang/php_${lang}.json`]();
        }
    })
    .mount('#app');
```

Is this a bug, or just a documentation issue? Thanks for your help!

**Comment by xiCO2k** [comment]
Do you have any `.json` lang files or only the `.php` lang files.

**Comment by stevebauman** [comment]
Thanks for the reply @xiCO2k! 🙏 

Only `.php` lang files, no `.json` files at all 👍

**Comment by xiCO2k** [comment]
got it, will take a look on that case!

**Comment by xiCO2k** [comment]
Hey @stevebauman sorry for the delay on this. 

I did a try on this repo: https://github.com/xiCO2k/laravel-vue-i18n-app and I did not got the error message.

Can you check if the error is still there, and if possible replicate on this repo?

Thanks

**Comment by paulelpidorou** [comment]
Probably related to this, but i am getting a similar error when setting up using Laravel and Inertiajs

![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/59161776/80d53434-f991-4759-af95-bb21c3d5d449)

Translations still work but i get the error.

The app.js configuration

```
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`,
        import.meta.glob('./Pages/**/*.vue')),
    setup ({el, App, props, plugin}) {
        return createApp({render: () => h(App, props)}).
        use(plugin).
        use(ZiggyVue).
        use(vfm).
        use(i18nVue, {
            resolve: async lang => {
                const langs = import.meta.glob('../../lang/*.json');
                return langs[`../../lang/${lang}.json`]();
            }
        }).
        use(VueGoogleMaps, {
            load: {
                key: googleMapsApiKey,
            },
        }).
        mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});
```

If I include a `php_ ` prefix as @stevebauman mentions everything works and error goes away.

**Comment by noor-tg** [comment]
@xiCO2k 

I did the same
```js
import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

createApp()
    .use(i18nVue, {
        resolve: async lang => {
            const langs = import.meta.glob('../../lang/*.json');

-           return await langs[`../../lang/${lang}.json`]();
+           return await langs[`../../lang/php_${lang}.json`]();
        }
    })
    .mount('#app');
```

and it is working.
so either needed to be fixed or change docs about it.

thanks for the awesome plugin
