### ISSUE TITLE
Library should work for nested keys in translation files. 

### ISSUE THREAD

**Issue by samir480** [xiCO2k/laravel-vue-i18n#157]
en.json
```
{
    "privacy": {
      "welcome": "Welcome to our Privacy Policy"
      
    }
}  
```

to use this I have to do this : `{{ $t('privacy').welcome }} `
but it should be workin with : ` {{ $t('privacy.welcome') }}`

**Comment by xiCO2k** [comment]
Hey @samir480 for the `json` translation it mimics the same logic from Laravel.

That works, on the `.php` lang files but not on the `.json` files.

Thanks
