### ISSUE TITLE
Ability to split language file into multiple objects

### ISSUE THREAD

**Issue by MeesPos** [xiCO2k/laravel-vue-i18n#16]
Is it possible to divide a translation file into multiple objects. So as an example:
`
"home": {
        "header": {
            "test": "test"
        },
        "description": "description"
    },
    "about-me": {
        "test": "test"
    }
}
`

And that you can then call those keys with `$t('home.header.test')`?

If this isn't possible yet, isn't that an idea for a new feature?

**Comment by xiCO2k** [comment]
@MeesPos will be working to add a loader to transform the php lang files into json
