### ISSUE TITLE
Console error after vue 3.4 update 

### ISSUE THREAD

**Issue by goale** [xiCO2k/laravel-vue-i18n#160]
After having updated vue to 3.4 I'm getting the following error in console:
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/4661017/24a9c3f8-d246-42c5-a5d3-1958362a24a5)
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/4661017/8b884970-ccb7-492d-9386-45026e955a71)

As far as I can see, the problem is caused by translation with replacements. Weirdly enough, translation seems to work even when the error happens.

When I downgrade vue back to 3.3, the error disappears. 

**Some context**
Line that causes the problem
```
$t('out of :total results', { total: totalFormatted })
```

Maybe it's related to 3.4 reactivity changes and `watchEffect` in `wTrans` method doesn't get called anymore

**Comment by xiCO2k** [comment]
Thanks for the report @goale.

Will check that case.

**Comment by xiCO2k** [comment]
Fixed and released on `v2.7.6`.

Thanks.
