### ISSUE TITLE
path.key not working at all

### ISSUE THREAD

**Issue by bmontassier** [xiCO2k/laravel-vue-i18n#164]
Hello, 

I have some issue with Laravel/Inertia/Vue latest

All my translations key with path. key not working.

For example 
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/35603054/65d12ca6-0e33-45a9-9642-3a848715e9af)
auth.login not return Log In but auth.login

If you can help me :)
Thanks, regards

**Comment by xiCO2k** [comment]
Hey @bmontassier for the `json` files it does not work as the same as for the `php` lang files, if you want multiple levels you should use the the `php` lang files.
