### ISSUE TITLE
Explain difference between trans, wTrans and $t?

### ISSUE THREAD

**Issue by guilheb** [xiCO2k/laravel-vue-i18n#166]
I have noticed that in `<script setup>`, sometimes `trans()` does not work as expected and we have to use `wTrans()`. Does anyone know why and when to use each?

Also, I see a `$t()` function in the documentation. What is this for?

**Comment by xiCO2k** [comment]
yes basically the `trans` method is not reactive, and the `wTrans` is reactive but you need to use with the `.value` syntax when you need.
