### ISSUE TITLE
Ability to use a folder with language files instead of 1 file

### ISSUE THREAD

**Issue by MeesPos** [xiCO2k/laravel-vue-i18n#17]
Is it possible to create a folder for a language, and that you can put multiple translation files in it?

**Comment by xiCO2k** [comment]
Hey @MeesPos, if you have something like that on a .json file on Laravel it will work? If so we can add that as new feature.

Thanks.

**Comment by MeesPos** [comment]
Yes, here is an example:

![image](https://user-images.githubusercontent.com/35431488/153965303-7dc912cb-1bfd-4e52-ade7-b23b1eb5d931.jpeg)

This is what you get when you init Laravel in your project.

Now you can get a translation with the following code: `__('auth.test')`.

**Comment by xiCO2k** [comment]
Yes with the php files, that is a feature needed to implement, to add a loader to transform the .php lang files to .json to be readable from the frontend.

But for the .json lang files I'm not sure if the multi level is supported (never tried).
