### ISSUE TITLE
Object Translation

### ISSUE THREAD

**Issue by RicardoRibeirorr** [xiCO2k/laravel-vue-i18n#171]
Hi,
I'm using object based translation like " $t('auth.failed') ", but its not working!

I've tested with single " $t("test") " and it works fine.

Template:
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/25754531/836ca9c7-1522-4bde-84ea-f733c21485be)

Translation "pt.json":
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/25754531/c02a4605-d3f9-4e7b-a8df-7d49d81385d7)

Result browser:
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/25754531/16e618ce-d218-40ff-a603-601a04a2d241)

Devtools json:
![image](https://github.com/xiCO2k/laravel-vue-i18n/assets/25754531/942ddebb-3910-4ceb-acca-a1f8f354c84c)

**Comment by valpuia604** [comment]
What happen if you put like `"auth.failed": "Failed message"`

**Comment by xiCO2k** [comment]
Hey @RicardoRibeirorr  you can not use the object syntax on `.json` files, only with `.php` files.

> **Main reason** is that is the way Laravel handles json language files in the backend.
