### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by HenestrosaDev** [xiCO2k/laravel-vue-i18n#174]
The error only happens when I access a page directly. For example, if I try to access `example.com/books` directly (which only uses `transChoice`), the page doesn't load and the exception is thrown. However, if I access `example.com` (which doesn't use `transChoice`) and then I access `example.com/books` from a `Link` Inertia component, then the page renders correctly.

I'm using Laravel 10 + Vue 3 + Inertia (`@inertiajs/vue3: 1.0.14` and `inertiajs/inertia-laravel: 0.6.11`). 

My `lang` directory structure is as follows:
```
├─ lang
     ├─ en
     │   └─ en.json
     └─ es
          └─ es.json
```

An excerpt of both files:

`es.json`
```
{ "book.count": ":count libro|:count libros" }
```

`en.json`
```
{ "book.count": ":count book|:count books" }
```

Isolated part of `resources/js/Pages/Book/Index.vue`, where the error occurs. I only use `transChoice` once here, with no trace of `trans`. The error also occurs in other pages that use `transChoice`. The pages that only use `trans` don't have any issue.

```vue
<script setup>
import { transChoice } from "laravel-vue-i18n";

defineProps({
    booksCount: {
        type: Number,
        required: true,
    },
});
</script>

<template>
    {{ transChoice("book.count", booksCount) }}
</template>
```
Even if I hardcode the booksCount value to 8, it still throws the same error.

The way I load the plugin from `app,js`:

```js
import { createApp, h } from "vue";
import { createInertiaApp, Link } from "@inertiajs/vue3";
import { resolvePageComponent } from "laravel-vite-plugin/inertia-helpers";
import { register } from "swiper/element/bundle";
import { i18nVue } from "laravel-vue-i18n";

register();

createInertiaApp({
    progress: {
        color: "#d62",
    },
    resolve: (name) => resolvePageComponent(
        `./Pages/${name}.vue`,
        import.meta.glob("./Pages/**/*.vue")
    ),
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(i18nVue, {
                resolve: async (lang) => {
                     const langs = import.meta.glob("../../lang/**/*.json");
                     return await langs[`../../lang/${lang}/${lang}.json`]();
                 },
            })
            .component("Link", Link)
            .mount(el);
    },
});
```

Exception:
```
laravel-vue-i18n.js?v=14ee09f0:10 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replace')
    at getPluralIndex (laravel-vue-i18n.js?v=14ee09f0:10:16)
    at choose (laravel-vue-i18n.js?v=14ee09f0:284:23)
    at laravel-vue-i18n.js?v=14ee09f0:629:49
    at ReactiveEffect.fn (chunk-CGJ6AWGQ.js?v=14ee09f0:1223:13)
    at ReactiveEffect.run (chunk-CGJ6AWGQ.js?v=14ee09f0:421:19)
    at get value (chunk-CGJ6AWGQ.js?v=14ee09f0:1234:64)
    at _I18n.transChoice (laravel-vue-i18n.js?v=14ee09f0:621:56)
    at Proxy.transChoice (laravel-vue-i18n.js?v=14ee09f0:377:35)
    at Proxy._sfc_render (Index.vue?t=1713967885542:72:67)
    at renderComponentRoot (chunk-CGJ6AWGQ.js?v=14ee09f0:2317:17)
```

I have another issue that I don't think is related to the above. I'll create another one if needed, but it basically happens when I set the language to "es" using the `loadLanguageAsync` and then refresh the page. The page is loaded in "en". It doesn't seem to store the language set by the user.

Thanks for your help and this awesome tool! Keep up the good work 💪

**Comment by HenestrosaDev** [comment]
Hi @xiCO2k. Have you had a chance to take a look at this? The issue still persists and I haven't figured out what's causing it yet. If you need more information, just let me know! Thanks again.

**Comment by xiCO2k** [comment]
Hey @HenestrosaDev sorry for the delay, can you create a repo with that exact error?

Thanks.

**Comment by HenestrosaDev** [comment]
Sure @xiCO2k! Here it is: https://github.com/HenestrosaDev/the-wordsmiths-collection

**Comment by xiCO2k** [comment]
Thanks will debug it!

**Comment by HenestrosaDev** [comment]
Hi @xiCO2k. Did you find anything relevant to the bug?

**Comment by xiCO2k** [comment]
sorry for the delay on that.

the issue is that you need to specify the language on load, you can add it here:

```diff
createApp({ render: () => h(App, props) })
    .use(plugin)
    .use(i18nVue, {
+	lang: 'es',
        resolve: async (lang) => {
	    const langs = import.meta.glob("../../lang/**/*.json");
	    return await langs[`../../lang/${lang}/${lang}.json`]();
    },
    })
    .component("Link", Link)
    .mount(el);
```

Or add it on the `<html lang="es">`.

That should solve it, but definitely I need to handler that error and show a different message or fallback to en.

Thanks.

**Comment by HenestrosaDev** [comment]
Thank you, that solves the exception in my first message! However, this still remains: 

>I have another issue that I don't think is related to the above. I'll create another one if needed, but it basically happens when I set the language to "es" using the loadLanguageAsync and then refresh the page. The page is loaded in "en". It doesn't seem to store the language set by the user.

Now the issue is the other way around, as the `lang` value now is "es". When I change the language to "en" using `loadLanguageAsync` and then refresh the page, the page loads in "es". Why doesn't the language change persist?

**Comment by HenestrosaDev** [comment]
> Now the issue is the other way around, as the `lang` value now is "es". When I change the language to "en" using `loadLanguageAsync` and then refresh the page, the page loads in "es". Why doesn't the language change persist?

I fixed this in [this commit](https://github.com/HenestrosaDev/the-wordsmiths-collection/commit/61b6849de42ef9a4666af06267e6b6d273d1983c) of my project.
