### ISSUE TITLE
Inject your package on Unit Test

### ISSUE THREAD

**Issue by zacktagnan** [xiCO2k/laravel-vue-i18n#176]
Hi:

Before including your translations package on the project, the Unit test I implemented was OK. But once I set the translate helpers on the Vue component called by the test, this test fails.

[ .tests/Unit/Habits/Info.test.js ]

    import { describe, it, expect, beforeEach } from "vitest";
    import { mount } from "@vue/test-utils";
    import HabitInfo from '@/components/Habit/Info.vue'

    describe('HabitInfo.vue', () => {
        let wrapper = null

        beforeEach(() => {
            wrapper = mount(HabitInfo, {
                props: {
                    name: 'Beber agua',
                    executions_count: 1,
                    times_per_day: 3,
                }
            })
        })

        it('displays the habit name', () => {
            expect(wrapper.find('#name').text()).toBe('Beber agua')
        })

        it('displays the habit executions', () => {
            expect(wrapper.find('#executions').text()).toBe('1 / 3 veces')
        })
    })

[ ./resources/js/components/Habit/Info.vue ]

    <script setup>
    import { transChoice } from 'laravel-vue-i18n';

    defineProps({
        name: {
            type: String,
        },
        executions_count: {
            type: Number,
        },
        times_per_day: {
            type: Number,
        },
    })
    </script>

    <template>
        <div class="flex flex-col basis-1/2">
            <h2 id="name" class="text-base font-semibold">{{ name }}</h2>
            <div class="flex">
                <small id="executions" class="font-normal text-gray-500">{{ executions_count }} / {{ times_per_day }} {{ transChoice('habits.index.list.times_per_day', times_per_day) }}</small>
            </div>
        </div>
    </template>

![imagen](https://github.com/xiCO2k/laravel-vue-i18n/assets/25615446/2af7dc2a-1cae-4b65-b0e3-de76b64ffda5)
![imagen](https://github.com/xiCO2k/laravel-vue-i18n/assets/25615446/365c5641-aa39-466a-8d88-4ac050954771)

It seems that it is necessary to inject the package on the test ... It seems that the problem is something similar that the one comented on this [post](https://github.com/kazupon/vue-i18n/issues/276). And, maybe, the solution is quite similar. But I don´t know how to act with your package.

So, do you know hao to solve the problem?

Greetings.

**Comment by xiCO2k** [comment]
will need to dig in a bit on this. Also if you find a way, let me know.

Thanks

**Comment by zacktagnan** [comment]
> will need to dig in a bit on this. Also if you find a way, let me know.
> 
> Thanks

OK... I will be attentive to any contribution you come to in your deepening of the case.
Regards.
