### ISSUE TITLE
New option to exclude framework translations 

### ISSUE THREAD

**Issue by thanosalexandris** [xiCO2k/laravel-vue-i18n#186]
Hey there. 
Could it be easy to add an extra option in `src/interfaces/plugin-options.ts` like this

```
excludeFrameworkTranslations: boolean,
```

and then in `src/vite.ts`
to change it into 
```
const excludeFrameworkTranslations = typeof options === 'string' ? options === 'lang' : options.excludeFrameworkTranslations ?? true
const frameworkLangPath = excludeFrameworkTranslations ? '' : 'vendor/laravel/framework/src/Illuminate/Translation/lang/'.replace('/', path.sep)
```

This way we'll be able to optionally skip framework translations, and having this `php_en.json` generated.

**Comment by xiCO2k** [comment]
Go ahead and make a PR for that, I will check.

Thanks for the suggestion.
