### ISSUE TITLE
Translation Keys Flash Before Rendering on Page Load or Refresh

### ISSUE THREAD

**Issue by khalednadam** [xiCO2k/laravel-vue-i18n#187]
When using laravel-vue-i18n with PHP translation files in a Laravel, Inertia.js, and Vue 3 application, translation keys are briefly visible for a second or less before being replaced by the actual translated content. This issue occurs on the initial page load or after refreshing the page.

To Reproduce Steps to reproduce the behavior:

Set up a Laravel application using Inertia.js and Vue 3.
Install and configure laravel-vue-i18n with PHP translation files.
Load any page with translations.
Observe that translation keys are briefly visible before the translated text appears.
Expected behavior The translated text should render immediately without showing the translation keys, even on initial load or after refreshing the page.

Environment:

Laravel Version: 11.25
Inertia.js Version: 1.0.0
Vue Version: 3.4
laravel-vue-i18n Version: 1.0
PHP Version: 8.3

**Comment by xiCO2k** [comment]
It can be solved if you use this instead of the lazy language loader:

```js
.use(i18nVue, {
    lang: 'pt',
    resolve: lang => {
        const langs = import.meta.glob('../../lang/*.json', { eager: true });
        return langs[`../../lang/${lang}.json`].default;
    },
})
```

Let me know if that works.
