### ISSUE TITLE
Concatenation in PHP language files causes an error in the loader

### ISSUE THREAD

**Issue by rafalglowacz** [xiCO2k/laravel-vue-i18n#24]
If I have a translation file like this:

```php
// lang/en/user.php

return [
    'lorem' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor " .  
               "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis.",
];
```

then I get the following error when running `npm run dev`:

> [webpack-cli] TypeError: Cannot read property 'kind' of undefined
>     at parseItem (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:60:14)
>    at parseItem (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:73:12)
>    at parseItem (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:71:36)
>    at /var/www/node_modules/laravel-vue-i18n/dist/loader.js:64:46
>    at Array.map (<anonymous>)
>    at parseItem (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:64:32)
>    at parse (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:56:32)
>    at /var/www/node_modules/laravel-vue-i18n/dist/loader.js:39:66
>    at Array.forEach (<anonymous>)
>    at parseAll (/var/www/node_modules/laravel-vue-i18n/dist/loader.js:38:14)

After removing `.` and turning the translation into a one-line string the problem disappears, but that's a workaround. Looking at the loader's source it seems that it might not be an easy fix, each part of the string is a separate item so they'd have to be buffered until the entire string is known. But maybe I missed something and it's actually not that hard. What do you think?

**Comment by rafalglowacz** [comment]
I took a crack at it and it turned out to be an easy fix. I've created a PR (#25).

**Comment by xiCO2k** [comment]
Thanks for the PR @rafalglowacz really appreaciate!
