### ISSUE TITLE
Resolve callback is required with Laravel Mix Plugin

### ISSUE THREAD

**Issue by stevebauman** [xiCO2k/laravel-vue-i18n#26]
Hi @xiCO2k, thanks for the great plugin! 🙏 

I'm wondering if/why the resolve callback is required even if we use the Laravel Mix plugin to import PHP files?

Is it possible to make this optional if my application only utilizes PHP based language files?

Thanks again for your time!

**Comment by xiCO2k** [comment]
Definitely something I should look on it. Great suggestion 💪.

Will dig in on that.

**Comment by stevebauman** [comment]
Awesome, thank you for the quick reply! 🙏

**Comment by xiCO2k** [comment]
Hey @stevebauman after digging it a lot on that, can't find a good way to have it full working.

If all the lang's are generated to the final build it can work, but if we want to use the lazy load when switching lang's, the import  needs to be on the client side 😞 .

**Comment by stevebauman** [comment]
No worries man, thanks for following up 😄 ❤️
