### ISSUE TITLE
Register Globally

### ISSUE THREAD

**Issue by zdarin** [xiCO2k/laravel-vue-i18n#28]
Hi, 

Im would like to make this plugin globally but something wrong not working can you help ??
Im trying to set but blank page appears

```
import { trans } from 'laravel-vue-i18n'

...
.mixin({ components: { trans } })
...

```

**Comment by xiCO2k** [comment]
Hey @zdarin I dont think that is the right way to implement mixins, check here: https://vuejs.org/api/options-composition.html#mixins

also you have `$t('string')`  available on the templates globally.

**Comment by zdarin** [comment]
thx
