### ISSUE TITLE
can't use with SSR because direct access to document property

### ISSUE THREAD

**Issue by ibrunotome** [xiCO2k/laravel-vue-i18n#3]
Hi.

If you try to build to server to get SSR, you will find this error:

<img width="790" alt="Screen Shot 2022-01-10 at 09 49 02" src="https://user-images.githubusercontent.com/4256471/148768499-edd5f342-d279-405a-95ad-832a77409fac.png">

A possible fix is check if the build is running for server or for browser: https://github.com/inertiajs/inertia/blob/master/packages/inertia/src/router.ts#L10

And only access the `document` property if is it running on browser.

**Comment by ibrunotome** [comment]
Also: after upgrade from 0.2.1 to 0.4.1:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/laravel-vue-i18n.js?v=4bc78461' does not provide an export named 'i18nVue'`

This happened with v3 also, rolling back to 0.2.1 it works again.

**Comment by xiCO2k** [comment]
v0.5.0 should have the support for the SSR.

Let me know if that works.

**Comment by ibrunotome** [comment]
> v0.5.0 should have the support for the SSR.
> 
> Let me know if that works.

yep, builded successfully. Thank you!

**Comment by xiCO2k** [comment]
Awesome! let me know about the export named issue
