### ISSUE TITLE
Infinite laravel mix alert in run watch

### ISSUE THREAD

**Issue by Ulrich15** [xiCO2k/laravel-vue-i18n#30]
Hi @xiCO2k , Thanks you for this helpful librairie.

But i face some issues. I install the librairie with Laravel and Vue3, in combinaision with LaravelMix. When i launch **npm run watch**, i'm pop with a ton of Laravel Mix alert of successful compilation. I don't know why. Thanks

**Comment by xiCO2k** [comment]
Thanks for reporting the issue! will definatelly take a look on that.

**Comment by xiCO2k** [comment]
Will try to find a solution for that, during the weekend, sorry for the delay.

**Comment by xiCO2k** [comment]
@Ulrich15 and @eminos having trouble replicating this case, can you share your webpack.mix.js file?

Thanks.

**Comment by Ulrich15** [comment]
@xiCO2k Morning
Nothing new yet ?

**Comment by xiCO2k** [comment]
Sorry @Ulrich15 did not found the time work on it, can you use `disableNotifications()` on mix for now?

Thanks

**Comment by xiCO2k** [comment]
Hey @Ulrich15 how many langs do you have on your app?

Thanks.

**Comment by xiCO2k** [comment]
Figure it out, should work now on `v1.4.4`

**Comment by Ulrich15** [comment]
> Figure it out, should work now on `v1.4.4`

Ah ok, let me try it

**Comment by Ulrich15** [comment]
the name i puted is `fr `and `en`

**Comment by xiCO2k** [comment]
@Ulrich15 sorry to bother you, can you send me a picture of the build?

Like this one:
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/823088/176164835-562efeb2-d18e-4710-b011-5a3aa149bc54.png">

Just to see if I can figure what is the issue still, thanks.

**Comment by Ulrich15** [comment]
Hi @xiCO2k 
No worry, happy to help to resolve some problems
There is the image of my complitation.

Just for informatio, when i run `npm run watch` for the first time, laravel mix just toast one time, but when i update de code, now it toast ever and ever.
 Thanks 🙏 


![image](https://user-images.githubusercontent.com/60409730/176174823-a0a1c5e3-93d7-4ec5-91d8-7bb1fe0b0af9.png)

**Comment by xiCO2k** [comment]
Hey @Ulrich15 any follow up on the issue?

**Comment by Ulrich15** [comment]
Hi @xiCO2k , Hoping you are good.
I updated the library to `version 2.1.3`, and when i run the `npm run watch` , i faced the same issues. Thanks

**Comment by xiCO2k** [comment]
Hey @Ulrich15 will need to test this out on windows can't replicate that on Mac or Linux. Will dig in on that, thanks for all the patience

**Comment by Ulrich15** [comment]
Hi @xiCO2k 
Is this problem be fixed? Thanks.

**Comment by Henxed** [comment]
Confirm. This problem exists only on Windows. Even after upgrading from 1.4.3 to 2.3.0. The "watch-poll" saves me. We also hope that this bug will be fixed.
