### ISSUE TITLE
This package or vue-i18n? Can't use both?

### ISSUE THREAD

**Issue by eminos** [xiCO2k/laravel-vue-i18n#31]
I was using the vue-i18n package primarily to format number strings.
https://vue-i18n.intlify.dev/
It seems I can't use both this package and vue-i18n since the APIs overlap somewhat (both use $t() helper for example).

Should I ditch vue-i18n and use something else for number formatting? Or is there some solution to be able to use both these packages? What are the advantages of `laravel-vue-i18n` over `vue-i18n`, apart from the php language files compilation?

Maybe you could add some clarification in the readme, since the names of these packages are so similar and someone might try to use both (like me :))

This is not a bug report, but I didn't know where I could ask these questions. I hope it's ok.

**Comment by xiCO2k** [comment]
I don't think you should mix both plugins together.

if you can, just use the `larave-vue-i18n` for both things.

**Comment by eminos** [comment]
But `laravel-vue-i18n` doesn't do number formatting, right? 
https://vue-i18n.intlify.dev/guide/essentials/number.html
It's not using `vue-i18n` under the hood or something?

**Comment by xiCO2k** [comment]
nope, but that could be a feature to be added.

Thanks for the input @eminos 💪
