### ISSUE TITLE
Translations with multiple words don't work

### ISSUE THREAD

**Issue by eminos** [xiCO2k/laravel-vue-i18n#33]
I have a strange issue where translations that have multiple words don't load. Only single word translations load.

I'm using Vite and the new laravel-vite-plugin like this:
```js
.use(i18nVue, {
    resolve: lang => {
        const langs = import.meta.globEager('../../lang/*.json');
        return langs[`../../lang/${lang}.json`];
    }
})
```

I don't like the flash of untranslated text when loading them async, so I do that instead. This part seems to work fine!

What's strange is the exported/loaded translation file looks like this:
![image](https://user-images.githubusercontent.com/1682784/176547391-7fdddf59-fa11-4a4a-b92d-b3096d1c978f.png)

Single word translations are set as a constants, and multi word translations are just strings.
This should still work, right?
But it doesn't for some reason.

```vue
// these translate fine
{{ $t('Search') }}
{{ $t('Filter') }}

// but these don't - and yes, they are available in the translation file
{{ $t('Confirm Password') }}
{{ $t('Price range') }}
{{ $t('Visit store') }} 
```

Any clue? Am I doing something wrong?

**Comment by eminos** [comment]
Hmm. I figured it out I think.
Doing this instead works:
```js
.use(i18nVue, {
    resolve: lang => {
        const langs = import.meta.globEager('../../lang/*.json');
        return langs[`../../lang/${lang}.json`].default;
    }
})
```
Notice the `.default`

**Comment by xiCO2k** [comment]
Awesome, nice find. Any issue let me know
