### ISSUE TITLE
spark folder is causing webpack compile error

### ISSUE THREAD

**Issue by thiago-tanaka** [xiCO2k/laravel-vue-i18n#35]
Hello, thank you for this library

this folder "spark" is causing an error
![image](https://user-images.githubusercontent.com/87078843/177043834-89f0642f-03cd-47ca-a8df-e219e5fe5974.png)

this is this error
![image](https://user-images.githubusercontent.com/87078843/177043913-45d81adb-c8be-4eba-8b2f-aa22a2bfb5d8.png)

is there any way to ignore this folder completely??

**Comment by xiCO2k** [comment]
Really interesting. will add a way to ignore certain folder names

**Comment by thiago-tanaka** [comment]
thank you so much :)

**Comment by xiCO2k** [comment]
Is now available on `v2.0.0`
