### ISSUE TITLE
How work with multiple language files

### ISSUE THREAD

**Issue by paulocastellano** [xiCO2k/laravel-vue-i18n#4]
Hello,

How i can work with multiple language files like:

```
lang/en/home.json
lang/en/pricing.json
lang/en/features.json

lang/pt/home.json
lang/pt/pricing.json
lang/pt/features.json
```

It's possible?

**Comment by xiCO2k** [comment]
Hey @paulocastellano there is no support for that, if you want to contribute with that will be glad to review it.

Thanks.

**Comment by paulocastellano** [comment]
@xiCO2k I will make it local, if works I send PR.

**Comment by xiCO2k** [comment]
Awesome Thanks
