### ISSUE TITLE
Vite Message: laravel-vue-i18n doesn't appear to be written in CJS

### ISSUE THREAD

**Issue by xreal** [xiCO2k/laravel-vue-i18n#41]
Hi @xiCO2k, 
i migrated yesterday to the Vite Integration. Everything's seems fine. Thanks for the fast adaption.

I noticed this message when use "vite build --ssr".

> laravel-vue-i18n doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by xiCO2k** [comment]
Thanks for the feedback @xreal 

Will try to figure that one out.

**Comment by xiCO2k** [comment]
Thanks @xreal for the feedback, should be solved now.
