### ISSUE TITLE
how to change active lang to the new locale 

### ISSUE THREAD

**Issue by ibrahimRezk** [xiCO2k/laravel-vue-i18n#45]
hello
i'm using the package and i can chang locale and files comes from Lang folder  can be changed to the new locale when using loadLanguageAsync()  function but i can't chang active lang  , it  is always 'en'
 also any translated data comming from database remain the same in english not to the new locale 
i am using astrotomic laravel translatable 
i tried to change locale in config/app manually to check that astrotomic is working fine and it is working .

any help
thank you

**Comment by xiCO2k** [comment]
if you pass the attribute lang on your `<html>` tag.

like `<html lang="{{ app()->getLocale() }}">` it should follow what `lang` you have set on the backend side.
