### ISSUE TITLE
Generate translations when using vite

### ISSUE THREAD

**Issue by ahuininga** [xiCO2k/laravel-vue-i18n#48]
Hi,

I'm using a new Laravel Jetstream application and am using vite. I've followed the readme, but the language json files aren't generated when running 'npm run build' (or npm run dev)

Which command should I run to generate the language json files?

**Comment by xiCO2k** [comment]
Hey @ahuininga, can you show me your `vite.config.js` file and your `app.js` file.

Thanks.

**Comment by andrey-helldar** [comment]
@ahuininga, you can also use the [publisher.laravel-lang.com](https://publisher.laravel-lang.com/installation/)

**Comment by ahuininga** [comment]
Vite config

https://github.com/ahuininga/mountain/blob/cd6d01a20e5f9e353efbf55a3bf31be350078e2e/vite.config.js#L1

App.js

https://github.com/ahuininga/mountain/blob/cd6d01a20e5f9e353efbf55a3bf31be350078e2e/resources/js/app.js#L1

**Comment by xiCO2k** [comment]
Thanks, will debug that.

**Comment by xiCO2k** [comment]
Hey @ahuininga, after debugging, looks like you are using the SSR Implementation and that is nothing wrong with that, but there will be no .json files generated.

You can use this `https://github.com/xiCO2k/laravel-vue-i18n#with-vite` with the `glob` instead of `globEager`.

Thanks.
