### ISSUE TITLE
Cannot read properties of undefined (reading 'VITE_LARAVEL_VUE_I18N_HAS_PHP')

### ISSUE THREAD

**Issue by andrey-helldar** [xiCO2k/laravel-vue-i18n#49]
- laravel-vue-i18n - 2.1.1
- vite - 2.9.9
- vuejs 3.2.25
- node 16.16.0
- without laravel

```
// .env

VITE_LARAVEL_VUE_I18N_HAS_PHP=false
```

```typescript
// src/main.ts

import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

import pinia from '@/utils/pinia'

createApp(App)
    .use(i18nVue, i18nOptions(pinia))
import i18nOptions from '@/utils/lang'
```

```typescript
// src/utils/lang

import { Pinia } from 'pinia'
import { useSettingsStore } from '@/stores/settings'

export default (pinia: Pinia) => {
    const lang = useSettingsStore(pinia).locale

    const resolve = async (lang: string) => {
        const files = import.meta.glob('../../lang/*.json')

        return await files[`../../lang/${ lang }.json`]()
    }

    return { lang, resolve }
}
```

![image](https://user-images.githubusercontent.com/10347617/180578306-75ceb7e5-dde2-4c32-9fd9-6519e001daf5.png)

Result: not working

![image](https://user-images.githubusercontent.com/10347617/180578509-1883480f-d066-4271-a7a8-ac9fc6583515.png)

If we add output to the console, we see that the files are loaded:

```typescript
const resolve = async (lang: string) => {
    const files = import.meta.glob('../../lang/*.json')

    console.log(files)
    console.log(
        import.meta.env.VITE_API_URL,
        import.meta.env.VITE_LARAVEL_VUE_I18N_HAS_PHP
    )

    return await files[`../../lang/${ lang }.json`]()
}
```

![image](https://user-images.githubusercontent.com/10347617/180578678-67815484-9dc2-4e36-ac41-2d5958c6adad.png)

![image](https://user-images.githubusercontent.com/10347617/180578701-ad812c4a-0147-403b-a42b-6dd933a5c7c1.png)

Without the `VITE_LARAVEL_VUE_I18N_HAS_PHP` key, I also get the error:

![image](https://user-images.githubusercontent.com/10347617/180578824-5587dde0-1be2-40c6-b4df-23c844b2ef6e.png)

Version 1.4.4 worked perfectly.

**Comment by xiCO2k** [comment]
Hey @andrey-helldar can you show me your `vite.config.js` file. Thanks.

**Comment by andrey-helldar** [comment]
Fix for this error:

```typescript
// node_modules/laravel-vue-i18n/dist/utils/has-php-translations.js:9
return import.meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP ? true : false;

// node_modules/.vite/deps/laravel-vue-i18n.js:348
return import_meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP ? true : false;
```

**Comment by andrey-helldar** [comment]
My `vite.config.ts` is:

```typescript
import vuetify from 'vite-plugin-vuetify'
import { defineConfig } from 'vite'
import { resolve } from 'path'

import vue from '@vitejs/plugin-vue'

export default defineConfig({
    resolve: {
        alias: {
            '@': resolve(__dirname, './src')
        }
    },
    plugins: [
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false
                }
            }
        }),
        vuetify({
            autoImport: true,
            styles: 'sass'
        })
    ],
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: `@import "./src/assets/styles/_variables";`
            }
        }
    }
})

```

**Comment by andrey-helldar** [comment]
I don't use Laravel in this project (this project only contains the frontend), so I didn't define the `i18n` plugin as the readme says it's for Lara.

![image](https://user-images.githubusercontent.com/10347617/180579357-4705bc23-d20d-4f24-ae5f-8fa9bdc27431.png)

**Comment by xiCO2k** [comment]
got it, that is an interesting use case, for sure will need to dig in more.

So you are just using the `*.json` lang files right?

**Comment by andrey-helldar** [comment]
> got it, that is an interesting use case, for sure will need to dig in more.
> 
> So you are just using the `*.json` lang files right?

Yes

https://github.com/volunteers-crm/web

**Comment by xiCO2k** [comment]
Can you try set on your `package.json` file

**Comment by andrey-helldar** [comment]
You probably didn't notice the comment [`above`](https://github.com/xiCO2k/laravel-vue-i18n/issues/49#issuecomment-1192996848).

Bug fixed by adding `i18n()` call to `vite.config.ts` file.

Thank you!

**Comment by andrey-helldar** [comment]
> Can you try set on your package.json file this:

Yes, I can

**Comment by andrey-helldar** [comment]
1. Removed `node_modules` and `package.lock`
2. Replace ` "laravel-vue-i18n": "^2.1.1"` with `"laravel-vue-i18n": "github:xiCO2k/laravel-vue-i18n"`
3. Run the `npm i` console command.
4. Check in browser
5. I see the error

![image](https://user-images.githubusercontent.com/10347617/180580097-dec6c364-e9f5-4082-b7ac-5ef8efb3ae34.png)

**Comment by xiCO2k** [comment]
really interesting case, will try to debug.

Thanks for all the help @andrey-helldar.

**Comment by andrey-helldar** [comment]
Next steps:

1. Go to `node_modules/laravel-vue-i18n/dist/cjs/utils/has-php-translations.js:22`
2. Replace line with `return typeof process.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP !== 'undefined' && process.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP ? true : false;`
3. Restart `vite`
4. Go to `node_modules/laravel-vue-i18n/dist/utils/has-php-translations.js:9`
5. Replace line with `return typeof import.meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP !== 'undefined' && import.meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP ? true : false;`
6. Remove the `node_modules/laravel-vue-i18n/dist/utils/has-php-translations.js.map` file
7. Restart `vite`
8. Go to `node_modules/.vite/deps/laravel-vue-i18n.js:348`
9. Replace line with `return typeof import_meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP !== "undefined" && import_meta.env?.VITE_LARAVEL_VUE_I18N_HAS_PHP ? true : false;`

Now, it's works

![image](https://user-images.githubusercontent.com/10347617/180580471-abccf8d6-a78e-40ad-ab30-5200f8bc8e88.png)

**Comment by andrey-helldar** [comment]
I was wrong. The problem is not solved :)

I forgot that I just changed files 😅

https://github.com/volunteers-crm/web/blob/main/vite.config.ts
```typescript
// vite.config.ts

import { defineConfig } from 'vite'
import { resolve } from 'path'

import i18n from 'laravel-vue-i18n/dist/vite'
import vuetify from 'vite-plugin-vuetify'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
    resolve: {
        alias: {
            '@': resolve(__dirname, './src')
        }
    },
    plugins: [
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false
                }
            }
        }),
        vuetify({
            autoImport: true,
            styles: 'sass'
        }),
        i18n()
    ],
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: `@import "./src/assets/styles/_variables";`
            }
        }
    }
})
```

https://github.com/volunteers-crm/web/blob/main/src/utils/lang.ts
```typescript
// src/utils/lang.ts

import { Pinia } from 'pinia'
import { useSettingsStore } from '@/stores/settings'

export default (pinia: Pinia) => {
    const lang = useSettingsStore(pinia).locale

    const resolve = async (lang: string) => {
        const files = import.meta.glob('../../lang/*.json')

        return await files[`../../lang/${ lang }.json`]()
    }

    return { lang, resolve }
}
```

https://github.com/volunteers-crm/web/blob/main/.env.example#L3
```
// .env

VITE_LARAVEL_VUE_I18N_HAS_PHP=false
```

And error)

![image](https://user-images.githubusercontent.com/10347617/180580798-bcef23a2-e83e-4605-a8e9-0de343afe427.png)

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/180581639-a93cc8c6-5308-4b93-8b2a-b520e4f08dab.png)

It's a simple: `import.meta.env` is undefined

**Comment by xiCO2k** [comment]
Thanks for the PR, can you try again, and let me know?

**Comment by andrey-helldar** [comment]
> Thanks for the PR, can you try again, and let me know?

If we add the `VITE_LARAVEL_VUE_I18N_HAS_PHP` variable key to the env file, then everything works. Everything works without it too.

![image](https://user-images.githubusercontent.com/10347617/180601035-1436f081-0c22-4c8b-9020-5b17480c9165.png)

Thank you!

**Comment by andrey-helldar** [comment]
By the way, so that the application does not load extra localizations during compilation, you can change the configuration:

### before
```javascript
import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

createApp()
    .use(i18nVue, {
        resolve: async lang => {
            const langs = import.meta.glob('../../lang/*.json');
            return await langs[`../../lang/${lang}.json`]();
        }
    })
    .mount('#app');
```

### after
```javascript
import { createApp } from 'vue'
import { i18nVue } from 'laravel-vue-i18n'

createApp()
    .use(i18nVue, {
        resolve: async lang => await import(`../../lang/${lang}.json`)
    })
    .mount('#app');
```

**Comment by xiCO2k** [comment]
So after the merge you got not problem?

**Comment by andrey-helldar** [comment]
When I wrote the code, there were no problems, but yesterday I could not check because npm and yarn gave an error installing dependencies when deleting the node_modules folder. I'll try again today.

**Comment by andrey-helldar** [comment]
> So after the merge you got not problem?

It's works:

![image](https://user-images.githubusercontent.com/10347617/180643156-fe8161b3-ae79-4ce1-a2ff-f93ae11789af.png)

**Comment by xiCO2k** [comment]
Awesome, will tag it
