### ISSUE TITLE
change locale(question)

### ISSUE THREAD

**Issue by merkBalevor** [xiCO2k/laravel-vue-i18n#54]
Good day, i try change locale like this:
import { loadLanguageAsync } from 'laravel-vue-i18n';

```
<template>
    <div>{{ $t('Welcome!') }}</div>
    <button @click="loadLanguageAsync('pt')">Change to Portuguese Language</button>
</template>
```

And i recive this error:
 Uncaught TypeError: _ctx.loadLanguageAsync is not a function
 Can you please tell me how to change the language?

**Comment by xiCO2k** [comment]
Hey @merkBalevor cant find any issue with that code, can you share more info on that file code?

Thanks

**Comment by merkBalevor** [comment]
I'm studying Vue and trying to make a multilingual application, I can't figure out how to do the language change? The documentation says it:

import { loadLanguageAsync } from 'laravel-vue-i18n';

```
<template>
    <div>{{ $t('Welcome!') }}</div>
    <button @click="loadLanguageAsync('pt')">Change to Portuguese Language</button>
</template>
```
, but I don't understand how use it, What code to use in the method? I will be very grateful to you if you show an example of a method for changing the language.

My app.blade.php

```
<html lang="{{str_replace('_', '-', app()->getLocale())}}">
My langs: en.json | en.json
```

My vue.js

```
@click="switchLanguageTo('en')"
import {i18nVue, loadLanguageAsync} from 'laravel-vue-i18n';
methods: {
    switchLanguageTo(lang) {
        // here i dont understand 
        loadLanguageAsync(lang);
        //  here i dont understand 
    },
},
```

**Comment by xiCO2k** [comment]
Hey @merkBalevor, you can check out this repo: https://github.com/xiCO2k/laravel-vue-i18n-webpack-app

I just commited an example of the change lang, any more help let me know.

**Comment by merkBalevor** [comment]
Thanks, you very help me, its work! I will be 10 times more grateful if it is possible not to reset the language after reloading the page, i.e. save to local storage

**Comment by xiCO2k** [comment]
So for that you can have a method to switch the locale and then on there
you can save to the localStorage and also run the `loadLanguageAsync`.

I would basically do that.
