### ISSUE TITLE
Create multiple instances for different locales?

### ISSUE THREAD

**Issue by ragulka** [xiCO2k/laravel-vue-i18n#56]
I have a use-case where I need to show part of an app in one language, and another part in another language - both being visible at the same time. Would this be possible with this package, somehow? I was hoping I could just create an instance of some sort of i18n class, but it looks like there is no class at all?

**Comment by ragulka** [comment]
Looking through the source code it seems multiple instances are not possible, not even when creating multiple Vue app instances, as this package maintains a single internal state, which is shared even between different vue app instances, unfortunately. Would you consider refactoring the package in a way that would allow creating different instances of the i18n state, each with its own messages & locale?

**Comment by xiCO2k** [comment]
Hey @ragulka, would love to review a PR with that capability.

Thanks
