### ISSUE TITLE
mix.version

### ISSUE THREAD

**Issue by noezdev** [xiCO2k/laravel-vue-i18n#57]
Using mix.version() will output app.js as the version as desired. But if you include this module here for example with mix.js('resources/js/app.js', 'public/js').vue().i18n().version(); at the end, after entering npm run prod, inside the app.js file are several (1-2) javascript files with seemingly random numbers, e.g. 501.js (without version behind it). In this 501.js file are all the translations that need to be done. Because there is no version number appended, this leads to the fact that the visitors have to empty the cache first after implementing new language variables.

Can these 501.js, 598.js etc. also be provided with version numbers?

**Comment by xiCO2k** [comment]
Hey @noezdev you need to set the `chunkFilename` on `webpackConfig` like this:

```js
mix.webpackConfig({
    output: {
        chunkFilename: 'js/[name].js?id=[chunkhash]',
    },
});
```
