### ISSUE TITLE
vite: module does not provide an export named 'i18nVue'

### ISSUE THREAD

**Issue by xiCO2k** [xiCO2k/laravel-vue-i18n#6]
Also: after upgrade from 0.2.1 to 0.4.1:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/laravel-vue-i18n.js?v=4bc78461' does not provide an export named 'i18nVue'`

This happened with v3 also, rolling back to 0.2.1 it works again.

_Originally posted by @ibrunotome in https://github.com/xiCO2k/laravel-vue-i18n/issues/3#issuecomment-1008974849_

**Comment by xiCO2k** [comment]
@ibrunotome can you share the vite configuration?

Can't find a way to replicate this one.

**Comment by ibrunotome** [comment]
> @ibrunotome can you share the vite configuration?
> 
> Can't find a way to replicate this one.

Sure, tested with v0.5.0 too:

My `vite.config.js`:

```js
const { resolve } = require('path')
import vue from '@vitejs/plugin-vue'

export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  publicDir: 'fake_dir_so_nothing_gets_copied',
  build: {
    manifest: true,
    outDir: resolve(__dirname, 'public/dist'),
    rollupOptions: {
      input: 'resources/scripts/app.ts',
      external: [
        resolve(__dirname, 'public/img')
      ],
    },
  },

  plugins: [vue()],

  resolve: {
    alias: {
      '@': resolve('./resources/scripts'),
    },
  },
})
```

My `resources/scripts/app.ts`

```ts
import '../css/app.css'
import Vue3TouchEvents from 'vue3-touch-events'
import mitt from 'mitt'
import { InertiaProgress } from '@inertiajs/progress'
import { createApp, h } from 'vue'
import { createInertiaApp } from '@inertiajs/inertia-vue3'
import { i18nVue } from 'laravel-vue-i18n'

const lang = document.documentElement.lang === 'pt_BR' ? 'br' : document.documentElement.lang

createInertiaApp({
  resolve: async (name) => {
    const pages = import.meta.glob('./Pages/**/*.vue')

    return (await pages[`./Pages/${name}.vue`]()).default
  },
  setup({ el, app, props, plugin }) {
    createApp({ render: () => h(app, props) })
      .use(plugin)
      .use(i18nVue, {
        lang: lang,
        resolve: (lang) => import(`../lang/${lang}.json`),
      })
      .use(Vue3TouchEvents, { disableClick: true })
      .provide('emitter', mitt())
      .mount(el)
  },
}).then(() => InertiaProgress.init({ color: '#059669' }))

```

My `package.json`

```json
{
  "private": true,
  "scripts": {
    "dev": "vite",
    "prod": "vite build && vite build --config vite.ssr.config.js",
    "lint:fix": "eslint ./resources --ext .js,.ts,.vue --quiet --fix",
    "lint:format": "prettier --loglevel warn --write \"./resources/**/*.{js,ts,vue}\" ",
    "lint": "yarn lint:format && yarn lint:fix "
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,ts,vue}": "eslint --fix && prettier --write"
  },
  "devDependencies": {
    "@headlessui/vue": "^1.2.0",
    "@heroicons/vue": "^1.0.1",
    "@inertiajs/inertia": "^0.11.0",
    "@inertiajs/inertia-vue3": "^0.6.0",
    "@inertiajs/progress": "^0.2.7",
    "@inertiajs/server": "^0.1.0",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/line-clamp": "^0.3.0",
    "@tailwindcss/typography": "^0.5.0",
    "@types/node": "^16.9.1",
    "@types/ziggy-js": "^1.3.0",
    "@typescript-eslint/eslint-plugin": "^4.28.0",
    "@typescript-eslint/parser": "^4.28.0",
    "@vitejs/plugin-vue": "^1.6.0",
    "@vue/compiler-sfc": "^3.0.7",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/server-renderer": "^3.2.26",
    "@vueuse/core": "^6.4.1",
    "autoprefixer": "^10.4.0",
    "axios": "^0.21",
    "chart.js": "^3.6.2",
    "chokidar": "^3.5.2",
    "dayjs": "^1.10.6",
    "eslint": "^7.29.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^7.11.1",
    "husky": "^6.0.0",
    "laravel-vue-i18n": "^0.5.0",
    "lint-staged": "^11.0.0",
    "litepie-datepicker": "^1.0.14",
    "mitt": "^3.0.0",
    "postcss": "^8.4.5",
    "postcss-import": "^12.0.1",
    "prettier": "^2.4.1",
    "prismjs": "^1.25.0",
    "tailwindcss": "^3.0.5",
    "ts-loader": "^9.2.3",
    "typescript": "^4.3.4",
    "v-lazy-image": "^2.0.1",
    "vite": "^2.6.0",
    "vue": "^3.2.0",
    "vue-chart-3": "^3.0.3",
    "vue-loader": "^16.1.2",
    "vue-the-mask": "^0.11.1",
    "vue-tsc": "^0.3.0",
    "vue3-touch-events": "^4.1.0",
    "ziggy-js": "^1.4.2"
  }
}
```

I'm getting an entire blank screen with the error:

<img width="1727" alt="Screen Shot 2022-01-11 at 20 30 51" src="https://user-images.githubusercontent.com/4256471/149037647-033c4162-7df2-4d5c-a730-d850e05abb50.png">

And it works normally if I rollback to v0.2.1

**Comment by xiCO2k** [comment]
Thanks, will debug it and get back to you.

**Comment by xiCO2k** [comment]
@ibrunotome can you go under`node_modules/laravel-vue-i18n/dist/index.js` and check on the bottom of the file for the:

```js
/**
 * The Vue Plugin. to be used on your Vue app like this: `app.use(i18nVue)`
 */
exports.i18nVue = {
    install: (app, currentOptions = {}) => {
        options = Object.assign(Object.assign({}, options), currentOptions);
        app.config.globalProperties.$t = (key, replacements) => trans(key, replacements);
        app.config.globalProperties.$tChoice = (key, number, replacements) => transChoice(key, number, replacements);
        loadLanguageAsync(options.lang);
    }
};
```

Let me know if that is in there? If not can you check your `node` version?

Thanks

**Comment by ibrunotome** [comment]
> @ibrunotome can you go under`node_modules/laravel-vue-i18n/dist/index.js` and check on the bottom of the file for the:
> 
> ```js
> /**
>  * The Vue Plugin. to be used on your Vue app like this: `app.use(i18nVue)`
>  */
> exports.i18nVue = {
>     install: (app, currentOptions = {}) => {
>         options = Object.assign(Object.assign({}, options), currentOptions);
>         app.config.globalProperties.$t = (key, replacements) => trans(key, replacements);
>         app.config.globalProperties.$tChoice = (key, number, replacements) => transChoice(key, number, replacements);
>         loadLanguageAsync(options.lang);
>     }
> };
> ```
> 
> Let me know if that is in there? If not can you check your `node` version?
> 
> Thanks

Yes, is there at line 129

My node is v17.3.0

**Comment by ibrunotome** [comment]
The presentation of the error on safari is a little different, but with the same blank screen.

<img width="382" alt="Screen Shot 2022-01-11 at 21 24 55" src="https://user-images.githubusercontent.com/4256471/149042168-aa5f602a-c2ed-49f5-8630-ee2861f6501d.png">

**Comment by ibrunotome** [comment]
That's the content of .vite/laravel-vue-i18n.js of v0.2.1

[v0.2.1.zip](https://github.com/xiCO2k/laravel-vue-i18n/files/7850982/v0.2.1.zip)

And for v0.5.0

[v.0.5.0.zip](https://github.com/xiCO2k/laravel-vue-i18n/files/7850991/v.0.5.0.zip)

**Comment by xiCO2k** [comment]
yes the problem was the change to compile with "node12"

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "node12",
    "outDir": "dist",
    "sourceMap": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipDefaultLibCheck": true
  },
  "files": [
    "./node_modules/@types/node/index.d.ts"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "rules": {
    "no-console": false
  }
}
```

That's needed to have the `defaultResolver` with the import (introduced in v0.3.0).

Trying to find a way to have it working well with vite and webpack.

Will keep you posted.

**Comment by xiCO2k** [comment]
Hey @ibrunotome can you check with v1.0.0, had to remove the defaultResolver in order to support both Laravel 8 an Laravel 9, lang path.

It also should fix your issue.

Let me know if it works.

**Comment by ibrunotome** [comment]
Yes, it worked! Thank you for spend your time with this.

**Comment by xiCO2k** [comment]
Awesome!
