### ISSUE TITLE
"npm run build" is slower than "npm run dev"

### ISSUE THREAD

**Issue by muhammedkaraoglu** [xiCO2k/laravel-vue-i18n#65]
Hello, first of all sorry for my English, I use google translate.

When I use "**npm run dev**", the translation process is done quickly without any problems, but when I do "**npm run build**", the file `"php_tr.32683819.js`" loads quite late depending on the internet speed. This causes "keys" to appear in the first opening of the page.

![resim_2022-09-10_000114141](https://user-images.githubusercontent.com/25641500/189445106-be152d7a-2fb6-4652-8294-2392607d1841.png)

As seen in the picture, "php_tr.32683819.js" file is loaded 2000ms after the page is opened.

![image](https://user-images.githubusercontent.com/25641500/189445880-deefb9c4-861e-4f90-a0b3-68397564d4a6.png)

Dependencies
"laravel-vue-i18n": "^2.2.2",
"vite": "^3.0.0",
 "vue": "^3.2.31"

Laravel 9+

##### vite.config.js
``` js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import i18n from 'laravel-vue-i18n/vite';


export default defineConfig({

    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        i18n(),
    ],
});

 ```

##### app.js
``` js
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, app, props, plugin }) {
        const captcheKey = props.initialPage.props.recaptcha_site_key;
        const application = createApp({ render: () => h(app, props) })
            .use(plugin)
            .use(i18nVue, {
                resolve: async lang => {
                    const langs = import.meta.glob('../../lang/*.json');
                    return await langs[`../../lang/${lang}.json`]();
                }
            })
    ...
```

**Comment by muhammedkaraoglu** [comment]
Is this a problem or is it my fault?  @xiCO2k

**Comment by xiCO2k** [comment]
Hey @muhammedkaraoglu can't find any relating with that delay, what is the filesize for that lang file?

**Comment by muhammedkaraoglu** [comment]
@xiCO2k  public/build/assets/php_tr.32683819.js   11.00 KiB / gzip: 2.62 KiB

The important thing is the "components" and "app.js" loading before the lang file.

**Comment by xiCO2k** [comment]
if you want to make sure it is not a "lazyLoad" you can use the `globEager` instead.

Check the SSR import suggestion: https://github.com/xiCO2k/laravel-vue-i18n#ssr-server-side-rendering

**Comment by muhammedkaraoglu** [comment]
> 

This worked for me, thanks a lot @xiCO2k  .

**Comment by xiCO2k** [comment]
no problem anytime.
