### ISSUE TITLE
Can't Install  laravel-vue-i18n

### ISSUE THREAD

**Issue by jobasc0** [xiCO2k/laravel-vue-i18n#68]
Hi, thanks a lot for this greate package, unfortunately i can's install it on fresh laravel install.
Here is the error log.
$ npm i laravel-vue-i18n
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: laravel-vue-i18n@2.2.2
npm WARN Found: laravel-mix@undefined
npm WARN node_modules/laravel-mix
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer laravel-mix@"^6.0.43" from laravel-vue-i18n@2.2.2
npm WARN node_modules/laravel-vue-i18n
npm WARN   laravel-vue-i18n@"*" from the root project
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/laravel-mix reason: Invalid response body while trying to fetch https://registry.npmjs.org/laravel-mix: read ECONNRESET

**Comment by xiCO2k** [comment]
Just tried that and there was no problems, can you check, what npm version you are using?

Thanks

**Comment by jobasc0** [comment]
$ npm -v
8.18.0
$ node -v
v16.17.0
