### ISSUE TITLE
Simple Question about the Json files

### ISSUE THREAD

**Issue by REJack** [xiCO2k/laravel-vue-i18n#72]
I don't know if some one asked it already, but do I need to mange the `.json`-files or should I only add/change language phrases inside the php files?

P.S.: Awsome work 😄 sadly I need to open a issue for it, due you have not enabled Github's discussion feature 😉

**Comment by xiCO2k** [comment]
you can use both translations if you use the vite plugin or the webpack plugin.

But I would say to just use the `.json` file for all the translations, thats what I would do.

Thanks.

**Comment by REJack** [comment]
Ok 😄 nice, I use the `.php`-files, it's better to handle for me 🤣 better to read and manage. But thanks for the info.
