### ISSUE TITLE
Translation not loaded on initial page load composition api

### ISSUE THREAD

**Issue by Mondotosz** [xiCO2k/laravel-vue-i18n#74]
Similarly to #62 , the translations aren't loaded yet when the composition api runs after the first page load.

Calling it inside of onMounted doesn't work either and I tried to make it work with the new onLoad callback from #70  but I didn't find a good way to do  it (can't find a way to force a refresh and using stores/:key works but it adds unnecessary boilderplate and sub optimal).

I'm wondering if it would be possible to fix it the same way as #62
another solution I could see is something like the onMounted hook

**Comment by xiCO2k** [comment]
Hey @Mondotosz will take a look on this.

**Comment by xiCO2k** [comment]
Check this reply https://github.com/xiCO2k/laravel-vue-i18n/issues/62#issuecomment-1275268441

**Comment by xiCO2k** [comment]
Thanks for the feedback
