### ISSUE TITLE
Register globally to use within script tags

### ISSUE THREAD

**Issue by robinvoor** [xiCO2k/laravel-vue-i18n#77]
Hi,

I noticed issue #28 - I was wondering if this is possible to register anything globally though. 
So instead of having to import `trans` each time (with `import { trans } from "laravel-vue-i18n"`), just use `trans` or `$t` or whatever immediately within the script tags like the following:

```js
<script setup>
const someTranslation = $t('global.something'); // like in <template>
// or
const someTranslation = trans('global.something');
</script>
```

**Comment by xiCO2k** [comment]
Hey @robinvoor you can make it available globally by using:

```js
import { trans } from "laravel-vue-i18n"

window.trans = trans;
```

No plans to add that to the plugin.

Thanks,
Francisco
