### ISSUE TITLE
Vapor support

### ISSUE THREAD

**Issue by phh** [xiCO2k/laravel-vue-i18n#8]
Hi there,

Is there any way of using this package together with [laravel-vapor](https://www.npmjs.com/package/laravel-vapor) to support the replaced URL's with the CDN instead?

**Comment by julianlaibach** [comment]
I think the following snippet (must be inserted in your webpack.mix.js) should solve this Problem it sets the correct Asset Url from the production .env file to be used. Its not tested yet.

```
if (mix.inProduction()) {
    const ASSET_URL = process.env.ASSET_URL + "/";

    mix.webpackConfig(webpack => {
        return {
            plugins: [
                new webpack.DefinePlugin({
                    "process.env.ASSET_PATH": JSON.stringify(ASSET_URL)
                })
            ],
            output: {
                publicPath: ASSET_URL
            }
        };
    });
}
```

**Comment by phh** [comment]
Currently trying that but seems like it's still trying to use the same URL rather than the CDN.

**Comment by phh** [comment]
Well. Vapor staging was running `npm ci && npm run dev && rm -rf node_modules` instead of prod. This fixed it!

Thanks!

**Comment by xiCO2k** [comment]
Thanks @julianlaibach
