### ISSUE TITLE
Switching language, including URL

### ISSUE THREAD

**Issue by xiki808** [xiCO2k/laravel-vue-i18n#82]
The `loadLanguageAsync` works great and I like it, but the URL doesn't change to reflect the language. Maybe I am missing something so I'm posting here. 

I know I can send an ajax call to get the same result, but would be nice if it works straight away through this functionality.

I'm using laravel 9 with Vite and Inertia.

**Comment by xiCO2k** [comment]
On full page reload?

If so, you can change the `<html lang="en">` argument.
