### ISSUE TITLE
HTML lang attribute value should use a hyphen instead of an underscore

### ISSUE THREAD

**Issue by ckyoung** [xiCO2k/laravel-vue-i18n#9]
When using a language that differ by territory like `zh-TW` the plugin seems to reset the HTML lang attribute to underscore version.

Screenshot:
![Screen Recording 2022-01-26 at 03 22 02 PM](https://user-images.githubusercontent.com/7137740/151120282-93e03d15-866a-49fc-89fb-c61356b315a1.gif)

`<html lang="zh_TW">`

Should really be:

`<html lang="zh-TW">`

Ref: https://tools.ietf.org/html/rfc5646#section-2.1

**Comment by NaincyKumariKnoldus** [comment]
Hey @ckyoung I have raised a PR for this. Please review that!
