### ISSUE TITLE
Multiple occurrences of variable

### ISSUE THREAD

**Issue by slashforward-nl** [xiCO2k/laravel-vue-i18n#91]
I have a string with for example,

`Do you really want to block :name. After this :name won't be able to message you.`

First occurrence of :name is translated, second is not.

I used it in the following sentence:

`'Weet je zeker dat je :name wilt deblokkeren? :name kan dan weer berichten sturen.'`

Results in the following:

`Weet je zeker dat je adsasd wilt deblokkeren? :name kan dan weer berichten sturen.`

Thanks for the great plugin!

**Comment by xiCO2k** [comment]
Nice catch.

Will try to make a PR to fix this one.

**Comment by xiki808** [comment]
Hi, excuse me for reopening this, but the issue appears again
