### ISSUE TITLE
lang directory inside js folder not creating after npm run dev command.   

### ISSUE THREAD

**Issue by devbipu** [xiCO2k/laravel-vue-i18n#95]
Hi,
I'm using Laravel 9 & Vue3 with Vite, I've installed the plugin and also setup as per docs but after ruing the `npm run dev` command it's not creating the lang dir inside my js directory. 

### This is my configuration in the app.js file 

```
vueApp.use(i18nVue, {
	resolve: async lang => {
        const langs = import.meta.glob('../../lang/*.json');
        return await langs[`../../lang/${lang}.json`]();
    }
})
```

**Comment by xiCO2k** [comment]
Can't find a problem with that, can you show me the error message?

**Comment by devbipu** [comment]
No error message is showing. The app is running well. But I can't find the lang dir inside my app. I can find it. In the tutorial `lang` dir is created after running the command `npm run dev` but in my case, it's not creating the dir into my app.

**Comment by xiCO2k** [comment]
so for the tutorial the `lang` folder should be on the root of your project. and the `app.js` should be on `resources/js/app.js`, if thats the case everything should work.

**Comment by devbipu** [comment]
There has a `lang` dir in my root directory but it's Laravel default lang dir with PHP files. For Vue, it's might my in my `resources/js/app.js` as per the tutorial.  Should I send you a git repo of the code so you can review it?

**Comment by xiCO2k** [comment]
Yes can you create a public repo for me to check?

Thanks.

**Comment by devbipu** [comment]
This is the repo https://github.com/devbipu/Laravel-9-Vue-3-setup---vite 
Check it please

**Comment by xiCO2k** [comment]
Will check it out, and get back to you.

**Comment by xiCO2k** [comment]
Found it, so in order to use the `.php` translations you need to check this part of the documentation:

https://github.com/xiCO2k/laravel-vue-i18n#php-translations-available-on-vue

Cheers.

**Comment by devbipu** [comment]
Actually, I've to use JavaScript translation. But I can't get the lang dir for javascript :(
