### ISSUE TITLE
Npm run dev generate php_en.json file

### ISSUE THREAD

**Issue by SimonJ** [xiCO2k/laravel-vue-i18n#99]
Hi,

First and foremost really awesome package! nice job.

I have followed the installation for my Laravel 9 + Jetstream + Inertiajs application (all new installation)
But when i run `npm run dev` it only generates a php_en.json file but I have set the application to be **da** What can i have done wrong?
<img width="364" alt="Skærmbillede 2023-02-02 kl  20 35 57" src="https://user-images.githubusercontent.com/183790/216432549-39c90d1b-ebd3-43b7-9ea2-bb67584fd4cc.png">
<img width="451" alt="Skærmbillede 2023-02-02 kl  20 36 33" src="https://user-images.githubusercontent.com/183790/216432551-9abb0b50-ab13-4243-81a3-d533c616da1a.png">
<img width="197" alt="Skærmbillede 2023-02-02 kl  20 36 45" src="https://user-images.githubusercontent.com/183790/216432552-1ef0e7f1-08a3-4c44-b3f2-8812a20b7b42.png">
<img width="316" alt="Skærmbillede 2023-02-02 kl  20 37 20" src="https://user-images.githubusercontent.com/183790/216432554-e98b8183-b92e-4746-8b80-76523f65459a.png">

**Comment by Jacobtims** [comment]
Please read the README.md

> During the npm run dev execution time, the plugin will create some files like this php_{lang}.json on your lang folder. And to avoid that to be commited to your code base, I suggest to your .gitignore this like:

```lang/php_*.json```

**Comment by xiCO2k** [comment]
Thanks for the reply @Jacobtims.

Any more help let me know.

**Comment by SimonJ** [comment]
@Jacobtims @xiCO2k 
Thanks for your answer. I don't think i was clear.

The issue is that it generate english files and not the danish files.

As i understand it, it should generate php_da.json where da is my language

**Comment by Jacobtims** [comment]
Run `npm run dev` again

**Comment by SimonJ** [comment]
@Jacobtims I have done that multiple times and it still just generate the en file
